spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: SGA
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  # drop-first: true